### ISSUE TITLE
Can't desewrialize an array of simple object

### ISSUE THREAD

**Issue by FelicePollano** [karlseguin/Metsys.Bson#2]
I've got this test ( a Visual Studio test )

 [TestMethod]
        public void TestMethod1()
        {
            var x = new Simple() { Name = "Pasta", Value = 5 };

```
        var q = new Simple[] { x,x,x,x,x,x,x,x};
        var bytes = Bson.Serializer.Serialize(q);

        var z = Bson.Deserializer.Deserialize<Simple[]>(bytes);
    }
```

That fails with the following exception:

Test method Metsys.Bson.VStest.UnitTest1.TestMethod1 threw exception:  Metsys.Bson.BsonException: Deserialization failed: type Metsys.Bson.VStest.UnitTest1+Simple does not have a property named .

It apparently look for a property without name.

**Comment by karlseguin** [comment]
BSON only supports an object as the root. Unlike JSON, it does not support arrays. This is something that the Mongo team has said would eventually get fixed (but it's been a while).

It is possible to serialize it, but then it wouldn't be BSON anymore..and thus wouldn't work for any other BSON engine (like MongoDB).

**Comment by FelicePollano** [comment]
Thanks a lot for the quick reply. It sounds perfectly ok to me, just my ignorance on how BSON worl. Would'nt be better to throw when someone try to serialize a IEnumerable<T> and not a string?

**Comment by karlseguin** [comment]
Good idea, I just pushed the appropriate change :)

**Comment by FelicePollano** [comment]
Great, going to check out. Thanks a lot.
